app: scd

service: service02

frameworkVersion: '3'


provider:
  name: aws
  profile: saga_dev
  runtime: python3.11
  ecr:
   images:
    service02:
      path: ../
      file: ./docker/Dockerfile
      buildArgs:
        SRC_PATH: service02/ 


functions:
  meu_primeiro_servico:
    handler: service.handler
    events:
      - httpApi:
          path: /
          method: get
