app: scd

service: service02

frameworkVarsion: '3'


provide:
  name: aws
  runtime: python3.9

functions:
  meu_primeiro_servico:
    handler: service02.handler
    events:
      - httpApi:
          path: /
          method: get
