app: scd

service: service01

frameworkVersion: '3'


custom:
  ecrImage: service01

provider:
  name: aws
  runtime: python3.11
  ecr:
    images:
      service01:
        path: ../
        file: ./docker/Dockerfile
        buildArgs:
          SRC_PATH: service01/ 

functions:
  meu_primeiro_servico:
    image:
      name: ${self:custom.ecrImage}
      command:
        - service.handler
    events:
      - httpApi:
          path: /
          method: get
