name: Deploy Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: AWS Install
      run:  |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
            unzip -q /tmp/awscliv2.zip -d /tmp
            rm /tmp/awscliv2.zip
            sudo /tmp/aws/install --update
            rm -rf /tmp/aws/
    - name: AWS Configure
      run:  |  
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile saga_dev
            aws configure set ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile saga_dev
            aws configure set default.region us-east-1 --profile saga_dev
            aws configure set default.output json --profile saga_dev
    - name: serverless deploy
      uses: serverless/github-action@v3.2
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
